openapi: 3.0.3
info:
  title: Individual PAYE Test Support
  version: '2.1'
servers:
  - url: https://test-api.service.hmrc.gov.uk
paths:
  /individual-paye-test-support/sa/{utr}/benefits/annual-summary/{taxYear}:
    post:
      tags:
        - individual-paye-test-support
      summary: Create benefits summary test data
      description: Supports the [Individual Benefits API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-benefits) by creating benefits summary test data.
      operationId: createBenefitsSummaryTestData
      parameters:
        - name: utr
          in: path
          description: The 10 digit self assessment UTR for the individual.
          required: true
          style: simple
          schema: &ref_0
            type: string
            example: 2234567890
        - name: taxYear
          in: path
          description: The tax year for the benefits test data being created.
          required: true
          style: simple
          schema:
            pattern: ^[0-9]{4}-[0-9]{2}$
            type: string
            example: 2016-17
        - name: Accept
          in: header
          style: simple
          description: Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning) of the API to be used.
          schema: &ref_1
            type: string
            enum:
              - application/vnd.hmrc.2.1+json
          required: true
        - name: Content-Type
          in: header
          style: simple
          description: Specifies the format of the request body, which must be JSON.
          schema: &ref_2
            type: string
            enum:
              - application/json
          required: true
        - name: Authorization
          in: header
          style: simple
          description: An [OAuth 2.0 Bearer Token](/api-documentation/docs/authorisation/application-restricted-endpoints).
          schema: &ref_3
            type: string
            example: Bearer 59fc92c1cdf0b8ef1f138a702effdbd2
          required: true
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - title: individualPayeTestSupportSaBenefitsAnnualSummaryRequest
                  type: object
                  properties: &ref_12
                    scenario:
                      oneOf:
                        - title: firstScenario
                          enum: &ref_4
                            - HAPPY_PATH_1
                          type: string
                          description: Standard happy path test scenario (default)
                        - title: secondScenario
                          enum: &ref_6
                            - HAPPY_PATH_2
                          type: string
                          description: Happy path test scenario with only mandatory fields
                      description: The scenario to create test data for Individual Benefits
                  description: Create Individual Benefits summary test data request
            examples:
              happy-path-1:
                description: Payload for scenario HAPPY_PATH_1
                value: &ref_5
                  scenario: HAPPY_PATH_1
              happy-path-2:
                description: Payload for scenario HAPPY_PATH_2
                value: &ref_7
                  scenario: HAPPY_PATH_2
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                allOf:
                  - title: individualPayeTestSupportSaBenefitsAnnualSummaryResponse
                    required: &ref_13
                      - employments
                    type: object
                    properties: &ref_14
                      employments:
                        type: array
                        items:
                          title: employment
                          required:
                            - employerPayeReference
                          type: object
                          properties:
                            employerPayeReference:
                              type: string
                              description: The employer's PAYE reference.
                              example: 123/AB456
                            companyCarsAndVansBenefit:
                              type: number
                              description: The total value of company cars and vans.
                              example: 44
                            fuelForCompanyCarsAndVansBenefit:
                              type: number
                              description: The total value of fuel for company cars and vans.
                              example: 99
                            privateMedicalDentalInsurance:
                              type: number
                              description: The total value of private medical and dental treatment and insurance.
                              example: 64
                            vouchersCreditCardsExcessMileageAllowance:
                              type: number
                              description: The value of benefits in the form of vouchers, credit cards and excess mileage allowance.
                              example: 80
                            goodsEtcProvidedByEmployer:
                              type: number
                              description: The total value of goods and other assets provided by the employer.
                              example: 125
                            accommodationProvidedByEmployer:
                              type: number
                              description: The total value of accommodation provided by the employer.
                              example: 375
                            otherBenefits:
                              type: number
                              description: The total value of other benefits, including interest-free loans and loans below the HMRC official rates.
                              example: 16
                            expensesPaymentsReceived:
                              type: number
                              description: The value of expenses payments received and balancing charges.
                              example: 415
                        description: An unordered list of one or more employments for which the taxpayer reported any benefits for the given tax year
                    description: Create Individual Benefits summary test data response
              examples:
                happy-path-1:
                  description: Response for scenario HAPPY_PATH_1 with all fields present
                  value:
                    employments:
                      - employerPayeReference: 123/AB456
                        companyCarsAndVansBenefit: 44
                        fuelForCompanyCarsAndVansBenefit: 99
                        privateMedicalDentalInsurance: 64
                        vouchersCreditCardsExcessMileageAllowance: 80
                        goodsEtcProvidedByEmployer: 125
                        accommodationProvidedByEmployer: 375
                        otherBenefits: 16
                        expensesPaymentsReceived: 415
                      - employerPayeReference: 456/AB456
                        companyCarsAndVansBenefit: 50
                        fuelForCompanyCarsAndVansBenefit: 249
                        privateMedicalDentalInsurance: 75
                        vouchersCreditCardsExcessMileageAllowance: 23
                        goodsEtcProvidedByEmployer: 250
                        accommodationProvidedByEmployer: 275
                        otherBenefits: 87
                        expensesPaymentsReceived: 265
                happy-path-2:
                  description: Response for scenario HAPPY_PATH_2 with only mandatory fields present
                  value:
                    employments:
                      - employerPayeReference: 123/AB456
      deprecated: false
      security:
        - application-restricted: []
  /individual-paye-test-support/sa/{utr}/child-benefit-entitlement/annual-summary/{taxYear}:
    post:
      tags:
        - individual-paye-test-support
      summary: Create Child Benefit entitlement test data
      description: Supports the [Individual Benefits API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-benefits) by creating Child Benefit entitlement test data.
      operationId: createChildBenefitEntitlementTestData
      parameters:
        - name: utr
          in: path
          description: The 10 digit self assessment UTR for the individual.
          required: true
          style: simple
          schema: *ref_0
        - name: taxYear
          in: path
          description: The tax year for the Child Benefit entitlement test data that is being created. Although production data will only be available for a portion of the current Self Assessment year, that policy is not enforced for the data that is created in the sandbox environment by this operation.
          required: true
          style: simple
          schema:
            pattern: ^[0-9]{4}-[0-9]{2}$
            type: string
            example: 2025-26
        - name: Accept
          in: header
          style: simple
          description: Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning) of the API to be used.
          schema: *ref_1
          required: true
        - name: Content-Type
          in: header
          style: simple
          description: Specifies the format of the request body, which must be JSON.
          schema: *ref_2
          required: true
        - name: Authorization
          in: header
          style: simple
          description: An [OAuth 2.0 Bearer Token](/api-documentation/docs/authorisation/application-restricted-endpoints).
          schema: *ref_3
          required: true
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - title: individualPayeTestSupportChildBenefitEntitlementRequest
                  type: object
                  properties: &ref_15
                    scenario:
                      oneOf:
                        - title: firstScenario
                          enum: *ref_4
                          type: string
                          description: Standard happy path test scenario (default)
                        - title: happy404Scenario
                          enum: &ref_8
                            - HAPPY_PATH_2
                          type: string
                          description: Happy path test scenario for HTTP 404 response
                        - title: unhappy500Scenario
                          enum: &ref_9
                            - UNHAPPY_PATH_500
                          type: string
                          description: Unhappy path test scenario for HTTP 500 response
                      description: The scenario for which to create Child Benefit entitlement test data.
                  description: Create Child Benefit entitlement test data request
            examples:
              happy-path-1:
                description: Payload for scenario HAPPY_PATH_1
                value: *ref_5
              happy-path-2:
                description: Payload for scenario HAPPY_PATH_2
                value: &ref_10
                  scenario: HAPPY_PATH_2
              unhappy-path-500:
                description: Payload for scenario UNHAPPY_PATH_500
                value: &ref_11
                  scenario: UNHAPPY_PATH_500
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                allOf:
                  - title: individualPayeTestSupportChildBenefitEntitlementResponse
                    type: object
                    required:
                      - expectedStatus
                    properties:
                      expectedStatus:
                        type: number
                        description: The HTTP response status code that should be expected from the [Individual Benefits API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-benefits) in the specified scenario.
                        example: 200
                      expectedJson:
                        type: object
                        required:
                          - childBenefitEntitlement
                        properties:
                          childBenefitEntitlement:
                            type: number
                            description: The amount of Child Benefit entitlement.
                            example: 450.99
              examples:
                happy-path-1:
                  description: Response for scenario HAPPY_PATH_1, showing an amount of child benefit entitlement.
                  value:
                    expectedStatus: 200
                    expectedJson:
                      childBenefitEntitlement: 215.49
                happy-path-2:
                  description: Response for scenario HAPPY_PATH_2.
                  value:
                    expectedStatus: 404
                unhappy-path-500:
                  description: Response for scenario UNHAPPY_PATH_500.
                  value:
                    expectedStatus: 500
      deprecated: false
      security:
        - application-restricted: []
  /individual-paye-test-support/sa/{utr}/employments/annual-summary/{taxYear}:
    post:
      tags:
        - individual-paye-test-support
      summary: Create employment history test data
      description: Supports the [Individual Employment API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-employment) by creating employment history test data.
      operationId: createEmploymentHistoryTestData
      parameters:
        - name: utr
          in: path
          description: The 10 digit self assessment UTR for the individual.
          required: true
          style: simple
          schema: *ref_0
        - name: taxYear
          in: path
          description: The tax year for the employment test data being created.
          required: true
          style: simple
          schema:
            pattern: ^[0-9]{4}-[0-9]{2}$
            type: string
            example: 2016-17
        - name: Accept
          in: header
          style: simple
          description: Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning) of the API to be used.
          schema: *ref_1
          required: true
        - name: Content-Type
          in: header
          style: simple
          description: Specifies the format of the request body, which must be JSON.
          schema: *ref_2
          required: true
        - name: Authorization
          in: header
          style: simple
          description: An [OAuth 2.0 Bearer Token](/api-documentation/docs/authorisation/application-restricted-endpoints).
          schema: *ref_3
          required: true
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - title: individualPayeTestSupportSaEmploymentsAnnualSummaryRequest
                  type: object
                  properties: &ref_16
                    scenario:
                      oneOf:
                        - title: firstScenario
                          enum: *ref_4
                          type: string
                          description: Standard happy path test scenario (default)
                        - title: secondScenario
                          enum: *ref_6
                          type: string
                          description: Happy path test scenario with only mandatory fields
                      description: The scenario to create test data for Individual Employment
                  description: Create Individual Employment summary test data request
            examples:
              happy-path-1:
                description: Payload for scenario HAPPY_PATH_1
                value: *ref_5
              happy-path-2:
                description: Payload for scenario HAPPY_PATH_2
                value: *ref_7
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                allOf:
                  - title: IndividualPayeTestSupportSaEmploymentsAnnualSummaryResponse
                    required: &ref_17
                      - employments
                    type: object
                    properties: &ref_18
                      employments:
                        type: array
                        items:
                          title: employment
                          required:
                            - employerPayeReference
                            - employerName
                          type: object
                          properties:
                            employerPayeReference:
                              type: string
                              description: The employer's PAYE reference.
                              example: 123/AB456
                            employerName:
                              type: string
                              description: The name of the employer.
                              example: Company XYZ
                            offPayrollWorkFlag:
                              type: boolean
                              description: The value of OPW flag.
                              example: false
                        description: An unordered list of one or more employments which the taxpayer had in the given tax year.
                    description: Create Individual Employment summary test data response
              examples:
                happy-path-1:
                  description: Response for scenario HAPPY_PATH_1 with all fields present
                  value:
                    employments:
                      - employerPayeReference: 123/AB456
                        employerName: Company XYZ
                        offPayrollWorkFlag: true
                      - employerPayeReference: 456/AB456
                        employerName: Company ABC
                        offPayrollWorkFlag: false
                happy-path-2:
                  description: Response for scenario HAPPY_PATH_2 with only mandatory fields present
                  value:
                    employments:
                      - employerPayeReference: 123/AB456
                        employerName: Company XYZ
      deprecated: false
      security:
        - application-restricted: []
  /individual-paye-test-support/sa/{utr}/income/annual-summary/{taxYear}:
    post:
      tags:
        - individual-paye-test-support
      summary: Create annual income summary test data
      description: Supports the [Individual Income API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-income) by creating annual income test data.
      operationId: createAnnualIncomeSummaryTestData
      parameters:
        - name: utr
          in: path
          description: The 10 digit self assessment UTR for the individual.
          required: true
          style: simple
          schema: *ref_0
        - name: taxYear
          in: path
          description: The tax year for the income test data being created.
          required: true
          style: simple
          schema:
            pattern: ^[0-9]{4}-[0-9]{2}$
            type: string
            example: 2016-17
        - name: Accept
          in: header
          style: simple
          description: Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning) of the API to be used.
          schema: *ref_1
          required: true
        - name: Content-Type
          in: header
          style: simple
          description: Specifies the format of the request body, which must be JSON.
          schema: *ref_2
          required: true
        - name: Authorization
          in: header
          style: simple
          description: An [OAuth 2.0 Bearer Token](/api-documentation/docs/authorisation/application-restricted-endpoints).
          schema: *ref_3
          required: true
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - title: individualPayeTestSupportSaIncomeAnnualSummaryRequest
                  type: object
                  properties: &ref_19
                    scenario:
                      oneOf:
                        - title: firstScenario
                          enum: *ref_4
                          type: string
                          description: Standard happy path test scenario (default)
                        - title: secondScenario
                          enum: *ref_6
                          type: string
                          description: Happy path test scenario with only mandatory fields
                      description: The scenario to create test data for Individual Income
                  description: Create Individual Income summary test data request
            examples:
              happy-path-1:
                description: Payload for scenario HAPPY_PATH_1
                value: *ref_5
              happy-path-2:
                description: Payload for scenario HAPPY_PATH_2
                value: *ref_7
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                allOf:
                  - title: individualPayeTestSupportSaIncomeAnnualSummaryResponse
                    required: &ref_20
                      - pensionsAnnuitiesAndOtherStateBenefits
                      - employments
                    type: object
                    properties: &ref_21
                      pensionsAnnuitiesAndOtherStateBenefits:
                        allOf:
                          - title: pensionsAnnuitiesAndOtherStateBenefits
                            type: object
                            properties:
                              otherPensionsAndRetirementAnnuities:
                                type: number
                                description: The amount of income from pensions (other than State Pension), retirement annuities and taxable trivial payments.
                                example: 36.5
                              incapacityBenefit:
                                type: number
                                description: The amount of taxable Incapacity Benefit and contribution-based Employment and Support Allowance.
                                example: 980.45
                              jobseekersAllowance:
                                type: number
                                description: The amount of income from Jobseeker's Allowance.
                                example: 89.99
                              seissNetPaid:
                                type: number
                                description: The amount of income from the Self-Employment Income Support Scheme.
                                example: 55.55
                            description: Income from pensions, annuities and other state benefits.
                          - description: Income from pensions, annuities and other state benefits.
                      employments:
                        type: array
                        items:
                          title: employment
                          required:
                            - employerPayeReference
                            - payFromEmployment
                          type: object
                          properties:
                            employerPayeReference:
                              type: string
                              description: The employer's PAYE reference.
                              example: 123/AB456
                            payFromEmployment:
                              type: number
                              description: The amount of pay from this employment, taken from the P45 or P60.
                              example: 22500
                        description: An unordered list of zero or more employments for which the taxpayer received an income in the given tax year.
                    description: Create Individual Income summary test data request
              examples:
                happy-path-1:
                  description: Response for scenario HAPPY_PATH_1 with all fields present
                  value:
                    pensionsAnnuitiesAndOtherStateBenefits:
                      otherPensionsAndRetirementAnnuities: 36.5
                      incapacityBenefit: 980.45
                      jobseekersAllowance: 89.99
                      seissNetPaid: 55.55
                    employments:
                      - employerPayeReference: 123/AB456
                        payFromEmployment: 22500
                      - employerPayeReference: 456/AB456
                        payFromEmployment: 8650
                happy-path-2:
                  description: Response for scenario HAPPY_PATH_2 with only mandatory fields present
                  value:
                    pensionsAnnuitiesAndOtherStateBenefits: {}
                    employments:
                      - employerPayeReference: 123/AB456
                        payFromEmployment: 22500
      deprecated: false
      security:
        - application-restricted: []
  /individual-paye-test-support/sa/{utr}/tax/annual-summary/{taxYear}:
    post:
      tags:
        - individual-paye-test-support
      summary: Create tax summary test data
      description: Supports the [Individual Tax API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-tax) by creating annual tax test data.
      operationId: createTaxSummaryTestData
      parameters:
        - name: utr
          in: path
          description: The 10 digit self assessment UTR for the individual.
          required: true
          style: simple
          schema: *ref_0
        - name: taxYear
          in: path
          description: The tax year for the tax test data being created.
          required: true
          style: simple
          schema:
            pattern: ^[0-9]{4}-[0-9]{2}$
            type: string
            example: 2016-17
        - name: Accept
          in: header
          style: simple
          description: Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning) of the API to be used.
          schema: *ref_1
          required: true
        - name: Content-Type
          in: header
          style: simple
          description: Specifies the format of the request body, which must be JSON.
          schema: *ref_2
          required: true
        - name: Authorization
          in: header
          style: simple
          description: An [OAuth 2.0 Bearer Token](/api-documentation/docs/authorisation/application-restricted-endpoints).
          schema: *ref_3
          required: true
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - title: individualPayeTestSupportSaTaxAnnualSummaryRequest
                  type: object
                  properties: &ref_22
                    scenario:
                      oneOf:
                        - title: firstScenario
                          enum: *ref_4
                          type: string
                          description: Standard happy path test scenario (default)
                        - title: secondScenario
                          enum: *ref_6
                          type: string
                          description: Happy path test scenario with only mandatory fields
                      description: The scenario to create test data for Individual Tax
                  description: Create Individual Tax summary test data request
            examples:
              happy-path-1:
                description: Payload for scenario HAPPY_PATH_1
                value: *ref_5
              happy-path-2:
                description: Payload for scenario HAPPY_PATH_2
                value: *ref_7
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                allOf:
                  - title: individualPayeTestSupportSaTaxAnnualSummaryResponse
                    required: &ref_23
                      - pensionsAnnuitiesAndOtherStateBenefits
                      - refunds
                      - employments
                    type: object
                    properties: &ref_24
                      pensionsAnnuitiesAndOtherStateBenefits:
                        allOf:
                          - title: pensionsAnnuitiesAndOtherStateBenefits
                            type: object
                            properties:
                              otherPensionsAndRetirementAnnuities:
                                type: number
                                description: The amount of tax deducted from pensions (other than State Pension), retirement annuities and taxable trivial payments.
                                example: 36.5
                              incapacityBenefit:
                                type: number
                                description: The amount of tax deducted from Incapacity Benefit.
                                example: 980.45
                            description: Tax deducted from pensions, annuities and other state benefits.
                          - description: Tax deducted from pensions, annuities and other state benefits.
                      refunds:
                        title: refunds
                        type: object
                        properties:
                          taxRefundedOrSetOff:
                            type: number
                            description: The amount of Income Tax refunded or set off by HMRC or Jobcentre Plus.
                            example: 325
                      employments:
                        type: array
                        items:
                          title: employment
                          required:
                            - employerPayeReference
                            - taxTakenOffPay
                          type: object
                          properties:
                            employerPayeReference:
                              type: string
                              description: The employer's PAYE reference.
                              example: 123/AB456
                            taxTakenOffPay:
                              type: number
                              description: The amount of UK tax deducted from pay under this employment.
                              example: 890.35
                        description: An unordered list of zero or more employments for which the taxpayer had tax deducted in the given tax year.
                    description: Create Individual Tax summary test data request
              examples:
                happy-path-1:
                  description: Response for scenario HAPPY_PATH_1 with all fields present
                  value:
                    pensionsAnnuitiesAndOtherStateBenefits:
                      otherPensionsAndRetirementAnnuities: 36.5
                      incapacityBenefit: 980.45
                    refunds:
                      taxRefundedOrSetOff: 325
                    employments:
                      - employerPayeReference: 123/AB456
                        taxTakenOffPay: 890.35
                      - employerPayeReference: 456/AB456
                        taxTakenOffPay: 224.99
                happy-path-2:
                  description: Response for scenario HAPPY_PATH_2 with only mandatory fields present
                  value:
                    pensionsAnnuitiesAndOtherStateBenefits: {}
                    refunds: {}
                    employments:
                      - employerPayeReference: 111/AAA
                        taxTakenOffPay: 3000
      deprecated: false
      security:
        - application-restricted: []
  /individual-paye-test-support/{nino}/winter-fuel-payment-amount/annual-summary/{taxYear}:
    post:
      tags:
        - individual-paye-test-support
      summary: Create Winter Fuel Payment test data
      description: Supports the [Individual Benefits API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-benefits) by creating Winter Fuel Payment test data.
      operationId: createWinterFuelPaymentAmountTestData
      parameters:
        - name: nino
          in: path
          description: The National Insurance number for the individual.
          required: true
          style: simple
          schema:
            type: string
            pattern: ^[A-Z]{2}[0-9]{6}[A-Z]$
            example: SA123456A
        - name: taxYear
          in: path
          description: The tax year for the Winter Fuel Payment test data being created.
          required: true
          style: simple
          schema:
            pattern: ^[0-9]{4}-[0-9]{2}$
            type: string
            example: 2025-26
        - name: Accept
          in: header
          style: simple
          description: Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning) of the API to be used.
          schema: *ref_1
          required: true
        - name: Content-Type
          in: header
          style: simple
          description: Specifies the format of the request body, which must be JSON.
          schema: *ref_2
          required: true
        - name: Authorization
          in: header
          style: simple
          description: An [OAuth 2.0 Bearer Token](/api-documentation/docs/authorisation/application-restricted-endpoints).
          schema: *ref_3
          required: true
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - title: individualPayeTestSupportWinterFuelPaymentAmountRequest
                  type: object
                  properties: &ref_25
                    scenario:
                      oneOf:
                        - title: firstScenario
                          enum: *ref_4
                          type: string
                          description: Standard happy path test scenario (default)
                        - title: happy404Scenario
                          enum: *ref_8
                          type: string
                          description: Happy path test scenario for HTTP 404 response
                        - title: unhappy500Scenario
                          enum: *ref_9
                          type: string
                          description: Unhappy path test scenario for HTTP 500 response
                      description: The scenario for which to create Winter Fuel Payment test data.
                  description: Create Winter Fuel Payment test data request
            examples:
              happy-path-1:
                description: Payload for scenario HAPPY_PATH_1
                value: *ref_5
              happy-path-2:
                description: Payload for scenario HAPPY_PATH_2
                value: *ref_10
              unhappy-path-500:
                description: Payload for scenario UNHAPPY_PATH_500
                value: *ref_11
        required: true
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                allOf:
                  - title: individualPayeTestSupportWinterFuelPaymentAmountResponse
                    type: object
                    required:
                      - expectedStatus
                    properties:
                      expectedStatus:
                        type: number
                        description: The HTTP response status code that should be expected from the [Individual Benefits API](https://developer.service.hmrc.gov.uk/api-documentation/docs/api/service/individual-benefits) in the specified scenario.
                        example: 200
                      expectedJson:
                        type: object
                        required:
                          - winterFuelPaymentAmount
                        properties:
                          winterFuelPaymentAmount:
                            type: number
                            description: The Winter Fuel Payment amount.
                            example: 250.15
                    description: Create Winter Fuel Payment test data response
              examples:
                happy-path-1:
                  description: Response for scenario HAPPY_PATH_1, showing a Winter Fuel Payment amount.
                  value:
                    expectedStatus: 200
                    expectedJson:
                      winterFuelPaymentAmount: 300
                happy-path-2:
                  description: Response for scenario HAPPY_PATH_2, simulating no Winter Fuel Payment amount found for the NINO.
                  value:
                    expectedStatus: 404
                unhappy-path-500:
                  description: Response for scenario UNHAPPY_PATH_500.
                  value:
                    expectedStatus: 500
      deprecated: false
      security:
        - application-restricted: []
components:
  securitySchemes:
    application-restricted:
      type: oauth2
      description: HMRC supports OAuth 2.0 for authenticating [application-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints) API requests using an OAuth 2.0 Bearer Token in the Authorization header.
      flows:
        clientCredentials:
          tokenUrl: https://test-api.service.hmrc.gov.uk/oauth/token
          scopes: {}
  schemas:
    individualPayeTestSupportSaBenefitsAnnualSummaryRequest:
      title: individualPayeTestSupportSaBenefitsAnnualSummaryRequest
      type: object
      properties: *ref_12
      description: Create Individual Benefits summary test data request
    individualPayeTestSupportSaBenefitsAnnualSummaryResponse:
      title: individualPayeTestSupportSaBenefitsAnnualSummaryResponse
      required: *ref_13
      type: object
      properties: *ref_14
      description: Create Individual Benefits summary test data response
    individualPayeTestSupportChildBenefitEntitlementRequest:
      title: individualPayeTestSupportChildBenefitEntitlementRequest
      type: object
      properties: *ref_15
      description: Create Child Benefit entitlement test data request
    individualPayeTestSupportSaEmploymentsAnnualSummaryRequest:
      title: individualPayeTestSupportSaEmploymentsAnnualSummaryRequest
      type: object
      properties: *ref_16
      description: Create Individual Employment summary test data request
    individualPayeTestSupportSaEmploymentsAnnualSummaryResponse:
      title: IndividualPayeTestSupportSaEmploymentsAnnualSummaryResponse
      required: *ref_17
      type: object
      properties: *ref_18
      description: Create Individual Employment summary test data response
    individualPayeTestSupportSaIncomeAnnualSummaryRequest:
      title: individualPayeTestSupportSaIncomeAnnualSummaryRequest
      type: object
      properties: *ref_19
      description: Create Individual Income summary test data request
    individualPayeTestSupportSaIncomeAnnualSummaryResponse:
      title: individualPayeTestSupportSaIncomeAnnualSummaryResponse
      required: *ref_20
      type: object
      properties: *ref_21
      description: Create Individual Income summary test data request
    individualPayeTestSupportSaTaxAnnualSummaryRequest:
      title: individualPayeTestSupportSaTaxAnnualSummaryRequest
      type: object
      properties: *ref_22
      description: Create Individual Tax summary test data request
    individualPayeTestSupportSaTaxAnnualSummaryResponse:
      title: individualPayeTestSupportSaTaxAnnualSummaryResponse
      required: *ref_23
      type: object
      properties: *ref_24
      description: Create Individual Tax summary test data request
    individualPayeTestSupportWinterFuelPaymentAmountRequest:
      title: individualPayeTestSupportWinterFuelPaymentAmountRequest
      type: object
      properties: *ref_25
      description: Create Winter Fuel Payment test data request
